apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cosy-staging
resources:
- ../../base
- ingress.yaml
images:
- name: ghcr.io/magenta-mause/cosy-domain-provider-backend
  newTag: main-6e9f04d
- name: ghcr.io/magenta-mause/cosy-domain-provider-frontend
  newTag: staging-f92ba20
