apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cosy-prod
resources:
- ../../base
- ingress.yaml
images:
- name: ghcr.io/magenta-mause/cosy-domain-provider-backend
  newTag: 1.0.3
- name: ghcr.io/magenta-mause/cosy-domain-provider-frontend
  newTag: 1.0.6
