apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosy-prod-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Magenta-Mause/Cosy-Domain-Provider-Deployment.git
    targetRevision: main
    path: overlays/prod-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
