apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosy-staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  project: cosy-domain-provider
  source:
    repoURL: https://github.com/Magenta-Mause/Cosy-Domain-Provider-Deployment
    targetRevision: main
    path: overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: cosy-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
